[build]
  base = "frontend"
  command = "cd ../netlify && npm install && cd ../frontend && npm run build"
  publish = "build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "../netlify/functions"
