[build]
  base = "frontend"
  command = "npm run build" 
  publish = "frontend/build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "../netlify/functions"
